### ISSUE TITLE
`onAuthStateChange` should not send a request to set the session

### ISSUE THREAD

**Issue by hf** [nuxt-community/supabase-module#184]
You can just use `document.cookie`?

See: https://github.com/supabase/gotrue-js/issues/579

**Comment by j4w8n** [comment]
> You can just use `document.cookie`?
> 
> See: [supabase/gotrue-js#579](https://github.com/supabase/gotrue-js/issues/579)

I understand that `document.cookie` can be used, but "should not" seems to imply that the code is doing something wrong. Can you explain?
