### ISSUE TITLE
Update to use `useRuntimeConfig`

### ISSUE THREAD

**Issue by ikadix** [nuxt-community/supabase-module#22]
I think this module needs updating since the nitropack merge. 

[This file](https://github.com/nuxt-community/supabase-module/blob/main/src/runtime/server/api/session.ts#L3) needs updating to switch from `import config from '#config'` to the new `import { useRuntimeConfig } from '#nitro'`

### Version
@nuxtjs/supabase: : v0.1.5 
nuxt: 3.0.0-27470397.9ebea90

### Reproduction Link

https://stackblitz.com/edit/github-zshr3e-acedle?file=app.vue

### Steps to reproduce

Install the module and use the latest version of nuxt 3. 
Run the dev server.

### What is Expected?
Dev server runs.

### What is actually happening?
Several warns about `#config` and then an error 
```
 ERROR  [worker reload] [worker init]Package import specifier "#config" is not defined in package /home/projects/github-zshr3e-acedle/package.json imported from /home/projects/github-zshr3e-acedle/.nuxt/dev/index.mjs
 ```

**Comment by psto** [comment]
@ikadix I imagine the Nuxt team is having quite a busy day today, to say the least :wink: so I made a pull request based on your input (which solved the issue on my end). It's my first time contributing to a Nuxt module, so hopefully, everything will work out :crossed_fingers:

**Comment by Atinux** [comment]
Damn you are faster than me @psto :rocket:

**Comment by Atinux** [comment]
Fixed in https://github.com/nuxt-community/supabase-module/releases/tag/v0.1.7

Thank you for your help ❤️
