### ISSUE TITLE
[nitro] [request error] Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by procrates** [nuxt-community/supabase-module#24]
### Version

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.5.0`
- Nuxt Version:     `3.0.0-27491748.3186841`
- Package Manager:  `npm@8.4.1`
- Builder:          `vite`
- User Config:      `privateRuntimeConfig`, `modules`
- Runtime Modules:  `@nuxtjs/supabase@0.1.7`
- Build Modules:    `-`
------------------------------

### What is actually happening?

```
[nitro] [request error] Cannot read properties of undefined (reading 'name')
  at Module.useSupabaseToken (./.nuxt/dist/server/server.mjs:8157:39)  
  at Module.useSupabaseClient (./.nuxt/dist/server/server.mjs:2411:39)  
  at ./.nuxt/dist/server/server.mjs:2365:40  
  at fn (./.nuxt/dist/server/server.mjs:332:27)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:41:19)  
  at callWithNuxt (./.nuxt/dist/server/server.mjs:334:23)  
  at applyPlugin (./.nuxt/dist/server/server.mjs:289:29)  
  at Module.applyPlugins (./.nuxt/dist/server/server.mjs:299:11)  
  at async createNuxtAppServer (./.nuxt/dist/server/server.mjs:44:7)  
  at async renderToString (./node_modules/vue-bundle-renderer/dist/index.mjs:247:19)
```

**Comment by Atinux** [comment]
Do you have a reproduction please?

**Comment by procrates** [comment]
Very strange.. When i now tried to make a repro it worked. It seems like there was some caching issues? Maybe... 
I think it has something to do with the latest migration from #config to #nitro that failed in the latest @nuxtjs/supabase update.

**Comment by procrates** [comment]
I found the issue..

I did set:

    privateRuntimeConfig: {
        supabase: {
            supabaseUrl: process.env.SUPABASE_URL,
            supabaseKey: process.env.SUPABASE_KEY,
            supabaseServiceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY,
        }
    },

So does that mean when I set the supabase key in public or private runtimeconfig it overwrites the options from supabase?

**Comment by Atinux** [comment]
It does overwrites indeed, but you want to use publicRuntimeConfig actually, cc @larbish

**Comment by larbish** [comment]
@procrates Here are the options you can override with the `publicRuntimeConfig`: https://supabase.nuxtjs.org/#options

Concerning `SUPABASE_URL` and `SUPABASE_KEY`, you just have to set it in your `.env`.

**Comment by miguelramos** [comment]
I have the same problem and checked the code and seems that the destructor now is missing a level.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/495720/162855216-a8b1be3a-bd7d-40cd-ac81-420d863e301c.png">

<img width="631" alt="Screen Shot 2022-04-12 at 01 37 48" src="https://user-images.githubusercontent.com/495720/162855589-0caeeb53-8ab4-4da1-92d9-e7293b153a22.png">

And config is on .env file.
