### ISSUE TITLE
schema option

### ISSUE THREAD

**Issue by unolee** [nuxt-community/supabase-module#45]
I would like to access different schema NOT public so, I tried options in nuxt.cconfig like below;

**  supabase: {
    // Options
    schema: "other-schema",
  },**

And I am trying to access to supabase using useSupabaseClient() using v0.1.16.

But it shows erre like 
{
  message: 'relation "public.xxxx" does not exist',
  code: '42P01',
  details: null,
  hint: null
}

It means it still access schema public.

Hope to put this scema option to access othere schema or storage ...

**Comment by larbish** [comment]
@unolee Client options should be encapsulated in `client` field: https://supabase.nuxtjs.org/get-started#client

Can you try with:

```
supabase: {
  client: {
    schema: 'other-schema'
  }
}
```

**Comment by dtechmaster** [comment]
Hi, @larbish .
I am trying to set the schema option at runtime.  
can you help me on how can a do that?
eg: ....useSupabaseAuthClient({options}) or something like that?
