### ISSUE TITLE
How to check if user is logged in inside middleware?

### ISSUE THREAD

**Issue by phillipmohr** [nuxt-community/supabase-module#52]
Hey, I'm trying to check if the user is logged in inside my `middleware/auth.js`
And if he's not, I want to redirect him to `admin/login`.

How would I do that?

**Comment by larbish** [comment]
Hey @phillipmohr, you can check this [doc section](https://supabase.nuxtjs.org/advanced#auth-middleware).

**Comment by phillipmohr** [comment]
@larbish thanks!
