### ISSUE TITLE
 Named export 'w3cwebsocket' not found. The requested module 'websocket' is a CommonJS module

### ISSUE THREAD

**Issue by pi0** [nuxt-community/supabase-module#62]
(Issue reported by @jonnyparris and others in https://github.com/nuxt/framework/issues/6495)

### Version
@nuxtjs/supabase: 0.1.19
nuxt: 3.0.0-rc.8

### Reproduction Link

https://github.com/jonnyparris/bug-repro-nuxt3

### Steps to reproduce

- `yarn generate` (or `yarn build` and start server)

### What is actually happening?

Runtime fails with importing `websocket` which is an incompatible CommonJS package used by `@supabase/supabase-js` > `@supabase/realtime-js`

### Solution

Quick workaround: (updated with solution of @matthewmaribojoc in https://github.com/nuxt/framework/issues/6495#issuecomment-1215159091)

```js
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  build: {
    transpile: [process.env.NODE_ENV === 'production' ? 'websocket' : ''],
  }
})
```

There are several other solutions we can consider and I probably add a CJS fix to unenv that fixes this magically but I spotted we are using a library that is probably never used in server (SSR and Nitro) `@supabase/realtime-js`. We could avoid using supabase client in server by direct API or mock this specific module only for server.

**Comment by larbish** [comment]
Should be fixed in [v0.1.22](https://github.com/nuxt-community/supabase-module/releases/tag/v0.1.22)

**Comment by larbish** [comment]
Does this error occurs only on dev mode ? If yes, I think you are still adding the `build: { transpile: ['websocket'] }` in your `nuxt.config.ts`. You do not need it no more if you're using the last version of the module.

**Comment by mwohlan** [comment]
@larbish 

This also happens with a minimal reproduction (needs your supabase url and key inside the .env file): https://stackblitz.com/edit/github-xlcv1j?file=app.vue

**Comment by larbish** [comment]
Thanks for the reproduction @mwohlan, indeed there was still an error on dev mode, it should be fixed in `0.1.23` ! Hope you confirm it's good for you 👍

**Comment by yk-sgr** [comment]
I still get this error.

```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "lint": "eslint --max-warnings 0 .",
    "typecheck": "nuxt typecheck",
    "start": "NODE_ENV=production node .output/server/index.mjs"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config-typescript": "^12.0.0",
    "@nuxtjs/supabase": "^0.3.4-beta.0",
    "@nuxtjs/tailwindcss": "^6.4.0",
    "@types/node": "^18.11.18",
    "eslint": "^8.33.0",
    "nuxt": "^3.2.3",
    "typescript": "^4.9.5",
    "vue-tsc": "^1.0.24"
  },
  "dependencies": {}
}
```

**Comment by cirolosapio** [comment]
same here
