### ISSUE TITLE
Update demo with supabase 2.0

### ISSUE THREAD

**Issue by larbish** [nuxt-community/supabase-module#64]

**Comment by shiftlabs1** [comment]
Can this also show how to apply the new supabase types generated, since the instantiation of supabase client is abstracted within the composable.
I am referring to 
```
import { createClient } from '@supabase/supabase-js'
import { Database } from 'lib/database.types'

const supabase = createClient<Database>(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_ANON_KEY
)
```

**Comment by larbish** [comment]
Demo has been updated so I close this issue. @shiftlabs1 thanks for the proposal, feel free to propose something with types generation :smile:
